alias lb := buildLapis
alias llvmb := buildllvm
alias bpt := buildpt
alias b := build
alias c := clean
[no-cd]
build:
    cmake --build build
[no-cd]
clean:
    cmake --build build --target clean
buildllvm:
    cmake --build ${WORKSPACE}/llvmBuild --target llvm-headers \
        llvm-libraries  tools/mlir/python/all \
        mlir-headers mlir-libraries mlir-opt \
        mlir-translate llc FileCheck mlir-cpu-runner
buildLapis:
    cmake --build ${WORKSPACE}/lapisBuild -j
buildpt:
    cmake --build ${WORKSPACE}/ptMpiBuild -j --target install
